### ISSUE TITLE
z axis ordering

### ISSUE THREAD

**Issue by AndyWebster** [metafizzy/zdog#1]
Objects seems to jump ahead in the z-axis when viewed at certain angles.

Reduced test case: https://codepen.io/awebster/pen/Xwqqpx

The orange box is rendering in front of the blue cubes at various angles.

**Comment by davecap** [comment]
Is this considered [z-fighting](https://zzz.dog/extras#z-fighting)? I thought maybe adding the dots to a group (in your test case) would fix this. It kind of fixes it... but also adds a new z-fighting issue: https://codepen.io/anon/pen/RmBEVO

**Comment by Stanko** [comment]
That is by design, author described it here:
https://zzz.dog/extras#z-fighting

**Comment by AndyWebster** [comment]
Now the docs are released this is a non-issue.
