### ISSUE TITLE
Element overlay late

### ISSUE THREAD

**Issue by lolafrerot** [metafizzy/zdog#101]
Hello, here is my Fishy Fish : 

**Test case:** https://codepen.io/lolafrerot/pen/mdPzyNR

When the fish rotates, elements overlay are late. So my fish doesn't look like a real fish.. Can I do something about it ?  Did I do somthing wrong ? Does the order of my elements have an importance ?

Cdt, 

Lola

**Comment by sebinsuresh** [comment]
This is a known issue, known as "Z-fighting"
You can find more information about it here: [Link to Zdog documentation](https://zzz.dog/extras#z-fighting)

[My codepen fixing this issue for the eye shape](https://codepen.io/sebinsuresh/pen/VwKMjpb)
