### ISSUE TITLE
Images and Text?

### ISSUE THREAD

**Issue by ThariqS** [metafizzy/zdog#17]
This is a feature request.

I love the concept and I'm using it already, but just want to know, is it technically possible to create 3d text or to project images on shapes? For example, a flat circle with an image projected on it as a texture of sorts. I'm not sure if the engine would even allow that to happen.

**Comment by kotpal** [comment]
+1 for text

**Comment by ISNIT0** [comment]
👍 Text would be great

**Comment by desandro** [comment]
Thanks for this feature request.

>  is it technically possible to create 3d text

No. However, I do have another feature request for SVG path importing that could resolve this. See #16 

> project images on shapes?

In theory, yes, as you can fill shapes with gradients or patterns in canvas and SVG. But in practical terms, Zdog doesn't make this easy. For now, I'm going to pass on this feature.

I'm closing this issue. Follow #16 for text support.
