### ISSUE TITLE
1.0.2 release

### ISSUE THREAD

**Issue by Banou26** [metafizzy/zdog#19]
https://github.com/metafizzy/zdog/compare/master@%7B1day%7D...master#diff-42f69825340f0b5fa628d80900a46daaL33

Wasn't included in the 1.0.1 npm publish making it impossible to import the module via a bundler.
You probably published the package by mistake before making these changes.
Could you please re-publish the package with these changes ?

**Comment by Banou26** [comment]
Actually, this isn't only happening in `index.js`, i think all of the changes you commit for the 1.0.1 weren't published to npm.

**Comment by desandro** [comment]
Thanks for the heads up. These commits will be part of 1.0.2 release, which has not been made yet.

**Comment by desandro** [comment]
[v1.0.2](https://github.com/metafizzy/zdog/releases/tag/v1.0.2) has been released. Please update! Closing as fixed.
