### ISSUE TITLE
adding more shapes & calling scene.updateGraph() should always let the new shapes appear when rendered

### ISSUE THREAD

**Issue by dgholz** [metafizzy/zdog#21]
I'm filing this on behalf of The_Amp_Walrus (https://news.ycombinator.com/item?id=20047206), who has an example CodePen of https://codepen.io/anon/pen/QRZKxy

Since calling `scene.updateGraph()` caches the `flatGraph` on its first call (as part of `checkFlatGraph`, (https://github.com/metafizzy/zdog/blob/v1.0.1/js/anchor.js#L124)), subsequent calls to `updateGraph` don't update the `flatGraph` to match the children of the scene.

Could the flatmap always be updated whenever `updateGraph` is called?

**Comment by desandro** [comment]
Thanks for reporting this issue. This is indeed a bug. I'll have a fix up in the next couple days. The fix will be part of the 1.0.2 release

**Comment by desandro** [comment]
[v1.0.2](https://github.com/metafizzy/zdog/releases/tag/v1.0.2) has been released with a fix for these bug. Please update! Closing as fixed.

**Comment by dgholz** [comment]
lgtm
