### ISSUE TITLE
Support for sharp stroke corners

### ISSUE THREAD

**Issue by KernelPainc** [metafizzy/zdog#23]
In several SVG programs, you can set the corner type for stroke from three options: the current rounded corner one, a sharp corner one and a filleted one where it cuts off diagonally. I'm not sure about the feasibility of the last one because I'm not sure how well it would translate to three dimensions, but the sharp corner option would open up possibilities. 

Example from inkscape: 
![image](https://user-images.githubusercontent.com/12434477/58651711-e4ea1080-8309-11e9-90bb-738f3e57e5e8.png)

**Comment by desandro** [comment]
You would think it's as simple as just changing the line join and line cap settings. Here's the strutter with `butt` lineCap and `miter` lineJoin

![image](https://user-images.githubusercontent.com/85566/58661003-ba418d00-82f4-11e9-92d0-9e91b5ba7616.png)

See demo https://codepen.io/desandro/pen/b0c6f8382e0f848634562dd29bea6937

The round joins and caps give every shape a spherical volume, like hot dogs and burger patties. So all the strokes have the illusion of similar 3D volume. When you change the joins and caps to sharp corners, that illusion no longer works.

**Comment by KernelPainc** [comment]
Thanks, that makes sense.

**Comment by boardfish** [comment]
`Box`es make a nice alternative to other objects if you really want to keep sharp corners.

**Comment by Laravel-authenticationan** [comment]
> `Box`es make a nice alternative to other objects if you really want to keep sharp corners.





https://raceflushed.github.io/angular5/
