### ISSUE TITLE
Distance before z-index fighting occurs

### ISSUE THREAD

**Issue by MariuszDabrowski** [metafizzy/zdog#26]
Take a look at the example below:

**Test case:** https://codepen.io/MarioD/pen/XwymyW

* When the can's x is set to 10, the z-index fighting issue occurs
* When the can's x is set to 11 it behaves perfectly

Is this just a limitation of the engine, or is there a way to render the can close to the box without having the fighting issues?

I read through https://zzz.dog/extras#z-fighting but it seems that you are able to have shapes much closer than my example before you get the z-index fighting issue.

Thanks!

**Comment by desandro** [comment]
Hmm, this z-fighting bug feels like it shouldn't be happening. Thanks for bringing this to my attention. I'll have to dig in and see what's going on.

**Comment by bendablegears** [comment]
Something isn't quite right with the code that begins at
https://github.com/metafizzy/zdog/blob/c6165f0f50c322cfbf35786dde6e79c5cd08edbe/js/ellipse.js#L66
as I was able to place the cylinder flush with the box with no z-fighting after commenting that part out.

**Comment by desandro** [comment]
[v1.1.0 has been released with this fix added.](https://github.com/metafizzy/zdog/releases/tag/v1.1.0) Closing this issue
