### ISSUE TITLE
Zdog chat channel

### ISSUE THREAD

**Issue by eeropic** [metafizzy/zdog#29]
Gitter (https://gitter.im/) would be probably the simplest & straightforward at this point, and it would point to the repository. But it can be created only by the repo owner(s)

**Comment by desandro** [comment]
**Add a 👍  reaction** to this issue if you would like to see a chat channel or forum for Zdog. Do not add +1 comments — [They will be deleted](https://metafizzy.co/blog/use-github-reactions-delete-plus-1-comments/).

**Comment by desandro** [comment]
I have decided not to open a Zdog chat channel. Thanks for your feedback. Sorry to pass on this one.
