### ISSUE TITLE
Consider using a module bundler like Rollup or Webpack

### ISSUE THREAD

**Issue by lostfictions** [metafizzy/zdog#30]
Hey, thanks for this library! I love the design philosophy (embracing z-fighting!) and I'm excited to play around with it more.

Since you're the maintainer I think it's important for you to work in a code style that you're comfortable with. But I wanted to open discussion about the possibility of zdog using a module bundler like [Rollup](https://rollupjs.org/) or [Webpack](http://webpack.js.org/) -- or maybe even a zero-config tool like [Microbundle](https://github.com/developit/microbundle/) that "just works" and would require even less configuration than exists now.

I think there'd be a bunch of benefits:
- Smaller output sizes! Bundlers have gotten very good at shrinking package sizes down. Not only that, they enable patterns (like tree-shaking) for consumers of the library to opt in to even smaller bundle sizes on their end by picking and choosing only the parts they need from the library.
- Much easier for others to contribute, since modules are now a familiar, conventional default style for most JS developers.
- As a corollary, the current reliance on Make makes it difficult for people who aren't on Mac or Linux to contribute (and even those folks may have to install extra tools and learn something new and un-javascripty just to get started). As I noted, something like [microbundle](https://github.com/developit/microbundle/) might actually result in _less_ complicated configuration, not more.
- Better static analysis! Tools like [eslint](https://eslint.org/) (or [TS for JS](https://github.com/Microsoft/TypeScript/wiki/Type-Checking-JavaScript-Files)) can do a much better job of catching bugs when projects are set up in a more conventional way.
- Much easier to use external dependencies if you wanted to opt in to them in the future (for example, to simplify interaction code or polyfill functionality). For better or for worse, many libraries now assume you're using a bundler, especially if you don't want to pollute the global namespace or risk causing conflicts for a user of your library.
- You can use modern syntax without having to worry about lowest-common-denominator browser support.
- Relatedly, reduced boilerplate across all files! For example, [rect.js](https://github.com/metafizzy/zdog/blob/master/js/rect.js)'s length gets cut by about half:

  before:
  ```js
  ( function( root, factory ) {
    // module definition
    if ( typeof module == 'object' && module.exports ) {
      /* globals module, require */// CommonJS
      module.exports = factory( require('./shape') );
    } else {
      // browser global
      var Zdog = root.Zdog;
      Zdog.Rect = factory( Zdog.Shape );
    }
  }( this, function factory( Shape ) {

  var Rect = Shape.subclass({
    width: 1,
    height: 1,
  });

  Rect.prototype.setPath = function() {
    var x = this.width / 2;
    var y = this.height / 2;
    this.path = [
      { x: -x, y: -y },
      { x:  x, y: -y },
      { x:  x, y:  y },
      { x: -x, y:  y },
    ];
  };

  return Rect;

  }));
  ```

    after:
  ```js
  import Shape from './shape';

  export default class Rect extends Shape {
    width = 1
    height = 1

    setPath() {
      let x = this.width / 2;
      let y = this.height / 2;
      this.path = [
        { x: -x, y: -y },
        { x:  x, y: -y },
        { x:  x, y:  y },
        { x: -x, y:  y },
      ];
    }
  }
  ```

  And some files, like [index.js](https://github.com/metafizzy/zdog/blob/master/js/index.js) will basically disappear. No need to repeat each module's name four times anymore :)

**Comment by samjbmason** [comment]
I have brought up this in another issue https://github.com/metafizzy/zdog/issues/22 @desandro has started he prefers a smaller build tool and something that he is able to debug easily. However, I have created a Branch that you can see the link to further down in issue showing the work I have done in using rollup with Zdog and things may potentially change.

**Comment by desandro** [comment]
Thank you for this thoughtful suggestion. Zdog is a personal project for me. As such, I'd like to stick with my own preferences. Older browser support is a priority for me. I'm not too bothered with lowest-common-denominator code because it means that the code is more widely accessible without build tools. I'll repost my response on #22 https://github.com/metafizzy/zdog/issues/22#issuecomment-497344346 

> To elaborate, I prefer using lighter build tools that output near-identical build code rather than relying on heavy-weight bundlers like Webpack or Rollup. It's a trade-off. I'd rather deal with my own broken code than managing build-tool output. I realize it may seem misguided, but after a decade of supporting JS plugins, that's my current preference ¯\\\_(ツ)\_/¯

**Comment by desandro** [comment]
[v1.0.2](https://github.com/metafizzy/zdog/releases/tag/v1.0.2) has been released with ESLint added in place of JSHint.
