### ISSUE TITLE
Relative String Defined Path

### ISSUE THREAD

**Issue by Solifugus** [metafizzy/zdog#33]
This is a feature request -- a 3D Draw Command.

Back in the mid 1980's (when I first learned to program), we had a "draw" command that took a string a characters that defined a draw path (relative--not absolute position like SVG paths).   It was like an ultra short-hand for the Logo language.  In this language, you gave a sequence of instructions to a turtle crawling on the canvas, like turn 45 degree, move forward 100, lower pen..  etc..  

In the draw command, I created a lot of things like 2D game spaceships and swords and such.  I even created a scalable font for text that worked exceptionally well.  It was very easy to build things.. much more so than SVG's paths.  And it would be immensely useful if it were in 3D.  

2D draw commands were like this, example of a square (F=forward, R=right):

    draw "F100R90F100R90F100R90F100"

Now imagine extending that with:

D = define, e.g. "Dmyshape:", which names the shape "myshape" until the next "D".
U = use, e.g. "Umyshape;", which means to draw the shape named "myshape".
S = shape, e.g. "Smyshape;", which sets extrusions to that shape until changed to another.
F = forward, e.g. "F100", which means extrude 100 pixels forward
N = non-return, meaning when in front of "F", draw forward but keep the cursor local.
A = anchor, e.g. "Amyanchor;", which labels the cursor location to reference later..
T = return to anchor, e..g "Tmyanchor;" to return to it.. Or "NT" for draw to it but don't return.
R = turn right, e.g. "R45" for 45 degree turn right
L = turn left, e.g. "L90"...
Y = yaw, e.g. "Y45".. these are like flying an airplane (yaw, roll, and pitch)
R = roll..
P = pitch..
C = color, e.g. "CFFFFFF;" for white..

This kind of draw command makes it easier to imagine while drawing but also keeps the description small string memory foot-print, and enables easy programmatic manipulation of the object...  For example, I scaled the font I made back the 1980's by simply running through the string and performing math on the various numbers after "F".  It didn't always work, depending on how the letters and numbers were drawn but I quickly learned how to draw them so it would always work..  It was quite fun.  Programming was a lot more fun back then because programming languages were so much easier.. access to hardware was easier.. everything was easier... and therefore you had so much more power at your finger tips.

**Comment by desandro** [comment]
Hello, thanks so much for this proposal. Yeah, I could see how this language would be a lot terser than the current JavaScript object-based syntax. That said, if I'm going to implement another path syntax, it would likely be for SVG importing/exporting. See #16. I appreciate this suggestion but I'll have to pass on it for now.

**Comment by Solifugus** [comment]
I thought it was a long shot.  Thanks for at least considering it.  One day, I may make it.
