### ISSUE TITLE
How to change rotate origin

### ISSUE THREAD

**Issue by CHENXINNN** [metafizzy/zdog#36]
I was wondering how to change the rotation origin of a shape, is it possible?
Thank you!

**Comment by chrisgannon** [comment]
I believe you can create a Zdog Anchor, add your Shape to the Anchor, then offset the Anchor's position to change the Shape's pivot origin.

Demo:
https://codepen.io/chrisgannon/pen/a08709716a51d56fe2be644bfc72330f

Adding  `rect` to  `rectAnchor` and then offsetting `rect`'s Y position moves `rect` up by half its own height. Animating the `rectAnchor`'s X rotation makes `rect` appear to rotate around its top (0,0).

**Comment by CHENXINNN** [comment]
Oh I see, thank you Chrisgannon!
