### ISSUE TITLE
Hollow Cylinder (the Flower Pot Problem)

### ISSUE THREAD

**Issue by turbo** [metafizzy/zdog#42]
I'm trying to create a flower pot with procedurally generated flowers, however, I've been stopped in my tracks by z-fighting which I can not for the life of me figure out how to prevent.

Here's a minimal demo (refresh to get a new pot): https://codepen.io/turbodev/pen/OYqVVo

Now from that perspective, it looks pretty good. But tilting the view up will reveal issues with the z ordering of stems and pot rim. The pot rim is actually a stack of circles (the only way I could think of to create a hollow cylinder). Another problem is that when I use a group to fix the ordering, rim and stems are always in the wrong order, since the "back" and "front" parts of the rim should mask differently.

Is this shape just no possible with zDog? I can live with some z-fighting, but stems belong inside of the pot IMO 😄.

Any tips appreciated.

**Comment by eeropic** [comment]
Hmm. I'm not sure if I'm correct, but I tried to visualize the problem quickly,
maybe @desandro can fill us in on whether the z-order is calculated from each 
shapes "bounding box center" (marked blue in picture below) or based on their origins.
You could try splitting the circles into quarters, so their "centerpoint" won't be 
interpreted as "behind the plants" in certain viewpoints. My codepen fork doesn't fix it but perhaps can guide you further.

<img width="1266" alt="z-ordering" src="https://user-images.githubusercontent.com/6544296/58906350-654ab000-8714-11e9-82fc-8161dccf6c46.png">

https://codepen.io/eeropic/pen/xNeGoX

<img width="301" alt="pot-pieces" src="https://user-images.githubusercontent.com/6544296/58906266-36343e80-8714-11e9-9c1c-5c5634ba2433.png">

**Comment by turbo** [comment]
@eeropic First of all thanks for the time you invested in debugging this.

I did think of splitting the rings, but in my mind arrived at the apparently wrong conclusion that it wouldn't lead to an improvement. Ordering issues are rare enough in your verion that a complete 360 view doesn't have any states where the artifact is overly dramatic.

Not at my PC right now, but did you try adding the pot base cylinder (whose faces act as the "earth") back in and seeing how it interacts with the stems and rim? I think having the majority of the body build as a cylinder might also improve performance.

**Comment by desandro** [comment]
@eeropic has the right idea. Zdog's z-index calculation is naive. Z-index for each shape is calculated as the average z value of its points. It's not mathematically accurate, but its easy to implement. I am considering adding more algorithms to help address z-fighting, like sorting by farthest-z-last or closest-z-first.

Another solution is to break up the pot rim into a ring of Rects, similar to how you would in a polygonal model. This is the same idea as @eeropic's proposal, but a bit more better suited to resolve z-fighting as the z-index will be calculated further toward the radius of the pot. [See demo on CodePen](https://codepen.io/desandro/pen/RmOpoW)


![image](https://user-images.githubusercontent.com/85566/58923857-7b09a680-870f-11e9-9170-0f8c49383ceb.png)
