### ISSUE TITLE
Allow Bezier to have more points

### ISSUE THREAD

**Issue by Neon22** [metafizzy/zdog#45]
The current bezier path allows only for the two control points and an end point. I want to draw longer more complex lines.
Ideally allow me to add as many points as possible.
Or add a Bspline option and with N points.

**Comment by chrisgannon** [comment]
You can add in as many `bezier` arrays to a Shape as you like:

https://codepen.io/chrisgannon/pen/47f2c8b32e7077ae17eaddd0a125d597

**Comment by Neon22** [comment]
oh... sigh.. thanks Chris. Nice job BTW....
