### ISSUE TITLE
dragRotate broken on mobile Chrome

### ISSUE THREAD

**Issue by jh3y** [metafizzy/zdog#53]
So far with `Zdog` I've not had much luck with fluid `dragRotate` on anything other than desktop browser. If I try to drag on say Chrome on Android/iOS I can only drag a small amount before the drag stops. I've attached a GIF of the issue being replicated in the Chrome inspector.

![zdog drag issue](https://user-images.githubusercontent.com/842246/59029521-684db980-8856-11e9-8012-fd458ca01c7b.gif)

**Test case:** https://codepen.io/desandro/pen/YbrLaO / zzz.dog

I've taken a look through the code and think I have an idea of where to debug the issue. I'll see if I can put some time into it 👍

**Comment by turbo** [comment]
Same, the drag implementation does not work for me on mobile (iOS Safari and Android Chrome)

**Comment by desandro** [comment]
Thanks for reporting this issue. I'm not able to replicate it in iOS Safari or iOS Chrome. I'll have to take a look in desktop emulation.

**Comment by nikkop** [comment]
I have the same problem running Chrome on Android

**Comment by desandro** [comment]
Looks like this a [touch device issue — similar to this SO thread](https://stackoverflow.com/a/48254578/182183). We can resolve it with [`touch-action: none` CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action). I'll add a fix for the next release. In the meantime, you can add this CSS:

``` css
.zdog-canvas {
  touch-action: none;
}
```

**Comment by jh3y** [comment]
Should/Could I open a PR where that CSS is applied to the element?

**Comment by desandro** [comment]
@jh3y Thanks for the offer, but I got this one covered.

**Comment by jh3y** [comment]
Oh. Well was happy to open another small PR. I did open one up. Wouldn't you still want `touch-action` though if `PointerEvent` isn't available on `window`?
