### ISSUE TITLE
Multiple canvas animation don't work

### ISSUE THREAD

**Issue by gabdag** [metafizzy/zdog#56]
Hi!
It's very awesome library. 😄
One question, can i make **multiple animated canvas** in the same html page? 
Because when i create multiple canvas in single page, they are rendered but they aren't animated.
Thanks! 😺 👍

**Comment by nikkop** [comment]
👋 

Yes of course. What does your current code look like? You might be missing something.

I put together an example where it's working, have a look: [https://codepen.io/nikkop/pen/eaaaQO](https://codepen.io/nikkop/pen/eaaaQO)

**Comment by gabdag** [comment]
Thank you Nikkop! I found an error in my code 😅
