### ISSUE TITLE
IE11 support

### ISSUE THREAD

**Issue by desandro** [metafizzy/zdog#57]
I'd like to confirm IE11 support for v1. Looks like its not currently working.

**Comment by desandro** [comment]
[v1.1.0 has been released with a fix added.](https://github.com/metafizzy/zdog/releases/tag/v1.1.0). Still need to check in browser.

**Comment by a10k** [comment]
![image](https://user-images.githubusercontent.com/1458845/59522318-fe837e80-8eeb-11e9-99cd-65811bed7ef5.png)
IE 11 is weird as always, the rendering and interactions work great, but the layout looks broken though on the homepage.

**Comment by desandro** [comment]
Ah! Good news! Okay, I'm closing this bug as fixed. Zdog v1.1.0 works in IE11. The website ... does not
