### ISSUE TITLE
API Typo

### ISSUE THREAD

**Issue by clarknelson** [metafizzy/zdog#64]
**Test case:** https://codepen.io/desandro/pen/YbrLaO

This function displays in the documentation as "onDragStart" when it should read "onDragMove"
https://zzz.dog/api#dragger-ondragmove

**Comment by chrisgannon** [comment]
Same for `onDragEnd` on the same page.

**Comment by desandro** [comment]
Thanks for reporting this! This typo is fixed and will be updated shortly.

**Comment by clarknelson** [comment]
Thanks for the framework! It's kickass
