### ISSUE TITLE
Errors with Vue

### ISSUE THREAD

**Issue by bhaskar-nair2** [metafizzy/zdog#72]
I would like to use ZDog in my VueJS projects, but simply installing via NPM results in various errors, that said, there is no definite way to use it in such frameworks, any help?

**Comment by desandro** [comment]
I'm not a Vue expert. Can someone else chime in here?

Zdog is written in vanilla JavaScript with a straight-forward API. My hope is that it can work with other frameworks with little overhead.

**Comment by AlexandreBonaventure** [comment]
Hey a little bit of shameless self promotion here: I've just created this plugin for Vue https://github.com/AlexandreBonaventure/vue-zdog

**Comment by desandro** [comment]
@AlexandreBonaventure Thanks so much for creating this Vue wrapper. I'm linking to in [Extras - More resources](https://zzz.dog/extras#more-zdog-resources) and on the README. Email me yo@metafizzy.co if you like stickers
