### ISSUE TITLE
I need more interaction,such as:click,dbclick

### ISSUE THREAD

**Issue by zengleyi** [metafizzy/zdog#87]
I hope it can have more interaction with mouse or touch, so that I can use it for Internet of things scenarios.This will be a little Kawaii Internet of things scene, which will be very different.

**Comment by zengleyi** [comment]
I want to scroll the mouse wheel anywhere on the canvas, the image can use this point for origin to be zoomed in and out.perhaps add event on canvas element is a good idea,but how to use the point for the origin,i want to get right code. or give zdog  a native wheel event API.

**Comment by desandro** [comment]
Hello! [Zdog.Dragger](https://zzz.dog/api#dragger) provides a simple API for dragging interaction on the Zdog illustration. But if you need additional functionality, like clicking specific elements, you'll have to build that yourself. I'll leave that up to you!
