### ISSUE TITLE
smoke effects cause model flickering

### ISSUE THREAD

**Issue by zzj1804** [metafizzy/zdog#97]
Hi, I love zdog's style and I code a little game with zdog.
**Test case:** https://zzj1804.github.io/ra2-tower-war/game/

I add smoke effects when buildings get damaged, but it cause model flickering. How to fix it? Thank you!
https://github.com/zzj1804/ra2-tower-war/blob/master/game/js/model/Smoke.js
https://github.com/zzj1804/ra2-tower-war/blob/master/game/js/model/PrismTower.js#L40
https://github.com/zzj1804/ra2-tower-war/blob/master/game/js/model/TeslaCoil.js#L40

**Comment by gemgames** [comment]
HI! Sorry this has taken so long. The game is really cool, and I think there's just either an abundance of objects on screen (my computer was running the game at a reduced fps) or a ton of Z-fighting. The layering algorithm used in Zdog is not the best, and can cause that.

**Comment by zzj1804** [comment]
thanks, I will add a switch.

**Comment by desandro** [comment]
Just wanted to say thank you sharing your work. This is an incredible use of Zdog. I'm sorry to hear its not up to the task of a proper game 3D engine
