### ISSUE TITLE
AddTo can't change after creation of Zdog element

### ISSUE THREAD

**Issue by gemgames** [metafizzy/zdog#98]
If anyone knows how to change "Addto" to add a group to something, please let me know.
I am one of the guys working on their own Zdog Editor (I have a beta repository) and need this. 

**Test case:** https://codepen.io/gemgames/pen/qBbKjGK

**Comment by mootari** [comment]
Once an element has been instantiated, you need to call `.addChild()` on the new parent to reparent the element.

By the way: I highly recommend that you familiarize yourself with the zdog internals, starting with [Anchor](https://github.com/metafizzy/zdog/blob/master/js/anchor.js) and [Shape](https://github.com/metafizzy/zdog/blob/master/js/shape.js). You might also be interested in [this collection of Zdog helpers](https://observablehq.com/@mootari/zdog-helpers).

**Comment by gregja** [comment]
Hi @gemgames , I confirm what @mootari says, specially for the Anchor which is very useful if you want add to dynamically some items to an existing shape. 
@mootari : your Zdog helpers are great, very good job. I didn't see a repo about it on you github account, do you plan to create one ?

**Comment by mootari** [comment]
> I didn't see a repo about it on you github account, do you plan to create one ?

No, I don't think there's enough code to justify the effort. But I've just added an ISC license to the notebook.

**Comment by gemgames** [comment]
Thank you!
